2020-08-30 19:31:14,197 ERROR: Exception on /search [GET] [in c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Stan\Desktop\dev\microblog\app\main\routes.py", line 146, in search
    current_app.config['POST_PER_PAGE'])
ValueError: not enough values to unpack (expected 2, got 0)
2020-08-30 19:34:19,805 INFO: Microblog startup [in C:\Users\Stan\Desktop\dev\microblog\app\__init__.py:77]
2020-08-30 19:40:05,394 ERROR: Exception on /search [GET] [in c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Stan\Desktop\dev\microblog\app\main\routes.py", line 146, in search
    current_app.config['POST_PER_PAGE'])
  File "C:\Users\Stan\Desktop\dev\microblog\app\models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "C:\Users\Stan\Desktop\dev\microblog\app\search.py", line 25, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\elasticsearch\client\utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\elasticsearch\client\__init__.py", line 1617, in search
    body=body,
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\elasticsearch\transport.py", line 392, in perform_request
    raise e
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\elasticsearch\transport.py", line 365, in perform_request
    timeout=timeout,
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\elasticsearch\connection\base.py", line 301, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count')
2020-08-30 19:41:25,299 INFO: Microblog startup [in C:\Users\Stan\Desktop\dev\microblog\app\__init__.py:77]
2020-08-30 19:41:29,329 ERROR: Exception on /search [GET] [in c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Stan\Desktop\dev\microblog\app\main\routes.py", line 146, in search
    current_app.config['POST_PER_PAGE'])
  File "C:\Users\Stan\Desktop\dev\microblog\app\models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "C:\Users\Stan\Desktop\dev\microblog\app\search.py", line 25, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\elasticsearch\client\utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\elasticsearch\client\__init__.py", line 1617, in search
    body=body,
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\elasticsearch\transport.py", line 392, in perform_request
    raise e
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\elasticsearch\transport.py", line 365, in perform_request
    timeout=timeout,
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\elasticsearch\connection\base.py", line 301, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count')
2020-08-30 19:42:32,555 INFO: Microblog startup [in C:\Users\Stan\Desktop\dev\microblog\app\__init__.py:77]
